### ISSUE TITLE
[BUG] Github Copilot Chat 与 Aide 冲突

### ISSUE THREAD

**Issue by sean1832** [nicepkg/aide#109]
你好，
我发现如果开启 Aide插件则无法使用github copilot chat，会一直卡在这个界面，无法登录。
![image](https://github.com/user-attachments/assets/4a43cee9-70ca-4c8a-8e5e-c4b738d33346)

我不确定是github copilot chat的问题还是Aide的问题。但一下是Copilot Chat的报错。
如果关闭Aide，则github copilot可以正常登录使用。

```
2024-10-04 09:50:36.183 [error] SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.json (c:\Users\greedy\.vscode\extensions\nicepkg.aide-pro-1.19.0\node_modules\@langchain\core\dist\output_parsers\structured.js:51:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TT.authFromGitHubToken (c:\Users\greedy\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:299:7809)
    at TT._auth (c:\Users\greedy\.vscode\extensions\github.copilot-chat-0.21.0\dist\extension.js:656:2720)
```
谢谢。

btw, 这个插件很牛逼，很好用👍

**Comment by 21dczhang** [comment]
我也是有这个问题，关闭AIDE后Chat可以正常使用，请问有共存的方法吗？

**Comment by Zxis233** [comment]
出现一样的情况。请求修复。

**Comment by Guoxiang1** [comment]
同样的问题＋1

**Comment by ice345** [comment]
同样的问题，这个可以说是严重问题了(Warning)，请立即修复

**Comment by Achuan-2** [comment]
+1

**Comment by shuangmuaigwu** [comment]
同样的问题~

**Comment by stevezheng** [comment]
感觉作者已经弃坑了……

**Comment by 2214962083** [comment]
hotfix, pls update to 1.19.1
